WITH CTE AS (

SELECT 

STARTED_AT,
TO_TIMESTAMP(STARTED_AT) AS STARTED_AT_1,
DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
DAYNAME(TO_TIMESTAMP(STARTED_AT)) AS DAYNAME,

CASE 
WHEN DAYNAME(TO_TIMESTAMP(STARTED_AT)) IN ('Sat','Sun')
THEN 'WEEKEND'
ELSE 'BUSINESSDAY'
END AS DAY_TYPE,

MONTH(TO_TIMESTAMP(STARTED_AT)),

CASE 
WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (1)
THEN 'JANUARY'
WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (2)
THEN 'FEBURARY'
WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (3)
THEN 'MARCH'
WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (4)
THEN 'APRIL'
WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (5)
THEN 'MAY'
WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (6)
THEN 'JUNE'
WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (7)
THEN 'JULY'
WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (8)
THEN 'AUGUST'
WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (9)
THEN 'SEPTEMBER'
WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (10)
THEN 'OCTOBER'
WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (11)
THEN 'NOVEMBER'
WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (12)
THEN 'DECEMBER'
ELSE 'NOT IN CALANDER'
END AS MONTH_OF_YEAR,

CASE WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (12,1,2)
THEN 'WINTER'
WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (3,4,5)
THEN 'SPRING'
WHEN  MONTH(TO_TIMESTAMP(STARTED_AT)) IN (6,7,8)
THEN 'SUMMER'
ELSE 'AUTOMN'
END AS STATION_OF_YEAR,

{{function1('STARTED_AT')}},

{{get_season('STARTED_AT')}} AS SEASON_OF_YEAR,

{{day_type('STARTED_AT')}} AS DAY_TYPE2


FROM {{ ref('stg_bike') }}
WHERE STARTED_AT != 'started_at'
)

SELECT * FROM CTE